conditioning:
  method: ps
  params:
    scale: 0.3
    out_size: 64

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 4
  
  noise: 
    name: poisson
    rate: 1.0
